export const inputForms = [
	{
		type: 'text',
		name: 'pension',
		required: true,
		className: 'pension',
		labelText: '<p class="form-calc-text">Выход на пенсию, лет</p>',
	},
	{
		type: 'text',
		name: 'desiredIncome',
		required: true,
		className: 'pension',
		labelText: '<p class="form-calc-text">Желаемый пассивный доход в месяц в $</p>',
	},
	{
		type: 'text',
		name: 'hardPercentInPension',
		required: true,
		className: 'pension',
		labelText: '<p class="form-calc-text">Годовой сложный % после создания капитала</p>',
	},
	{
		type: 'text',
		name: 'incomeTax',
		className: 'pension',
		required: true,
		labelText: '<p class="form-calc-text">Налог на инвестиционный доход</p>',
	},
	{
		type: 'text',
		name: 'startCreateCapital',
		required: true,
		className: 'storage',
		labelText: '<p class="form-calc-text">Возраст начала создания капитала, лет</p> ',
	},
	{
		type: 'text',
		name: 'contribution',
		required: true,
		className: 'storage',
		labelText: '<p class="form-calc-text">Первоначальная инвестиция в $</p>',
	},
	{
		type: 'text',
		name: 'addMonth',
		required: true,
		className: 'storage',
		labelText: '<p class="form-calc-text">Добавления каждый месяц в $</p> ',
	},
	{
		type: 'text',
		name: 'hardPercentInYear',
		required: true,
		className: 'storage',
		labelText: '<p class="form-calc-text">Годовой сложный % в период создания капитала</p>',
	},
]
