export const inputForms = [
	{
		type: 'text',
		name: 'desiredIncome',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		min: '2',
		labelText: 'Желаемый доход в месяц в $',
	},
	{
		type: 'text',
		name: 'inflation',
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Уровень инфляции (для $)',
		disabled: true,
		value: '2.5%',
	},
	{
		type: 'text',
		name: 'desiredIncomeInflation',
		errorText: 'Enter login!',
		labelText: 'Желаемый доход в месяц в $ (с инфляцией)',
		disabled: true,
		value: 0,
	},
	{
		type: 'text',
		name: 'contribution',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Первоначальный вклад в $',
		// value: 1000,
	},
	{
		type: 'text',
		name: 'addMonth',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Ежемесячные добавления в $',
		// value: 1000,
	},
	{
		type: 'text',
		name: 'startCreateCapital',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Начало создания капитала, лет',
		// value: 25,
	},
	{
		type: 'text',
		name: 'pension',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Выход на пенсию, лет',
		// value: 50,
	},
	{
		type: 'text',
		name: 'quantityAccum',
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Количество лет накопления',
		disabled: true,
	},
	{
		type: 'text',
		name: 'hardPercentInYear',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Годовой сложный % в период накопления, $',
		value: '10%',
	},
	{
		type: 'text',
		name: 'percentMonth',
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Ежемес % в период накопления, $',
		disabled: true,
		value: 0,
	},
	{
		type: 'text',
		name: 'hardPercentInPension',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Годовой сложный % на пенсии, $',
		value: '10%',
	},
	{
		type: 'text',
		name: 'percentMonthPension',
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Ежемес % на пенсии, $',
		disabled: true,
		value: 0,
	},
	{
		type: 'text',
		name: 'summ',
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Сумма к моменту выхода на пенсию,$',
		disabled: true,
		value: 0,
	},
	{
		type: 'text',
		name: 'needInYear',
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Нужно в год',
		disabled: true,
		value: 0,
	},
];
