export const inputForms = [
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Желаемый доход в месяц в $',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Уровень инфляции (для $)',
		value: '2.5%',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		errorText: 'Enter login!',
		labelText: 'Желаемый доход в месяц в $ (с инфляцией)',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Первоначальный вклад в $',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Ежемесячные добавления в $',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Начало создания капитала, лет',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Выход на пенсию, лет',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Количество лет накопления',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Годовой сложный % в период накопления, $',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Ежемес % в период накопления, $',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Годовой сложный % на пенсии, $',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Ежемес % на пенсии, $',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Сумма к моменту выхода на пенсию,$',
	},
	{
		type: 'text',
		name: 'user-login',
		required: true,
		className: 'form-control',
		errorText: 'Enter login!',
		labelText: 'Нужно в год',
	},
	{
		type: 'submit',
		name: 'submit',
		// value: 'calculate',
	},
];
