export const inputForms = [
	{
		type: 'text',
		name: 'desiredIncome',
		required: true,
		className: 'pension',
		errorText: 'Enter login!',
		labelText: 'Желаемый пассивный доход в месяц в $ <span class="star">*</span>',
	},
	{
		type: 'text',
		name: 'inflation',
		className: 'pension',
		errorText: 'Enter login!',
		labelText: 'Уровень инфляции (для $)',
		disabled: true,
		value: '2.5%',
	},
	{
		type: 'text',
		name: 'desiredIncomeInflation',
		className: 'pension',
		errorText: 'Enter login!',
		labelText: 'Желаемый пассивный доход в месяц в $ (с инфляцией)',
		disabled: true,
		value: 0,
	},

	{
		type: 'text',
		name: 'hardPercentInPension',
		required: true,
		className: 'pension',
		errorText: 'Enter login!',
		labelText: 'Годовой сложный % после создания капитала <span class="star">*</span>',
		value: '10%',
	},
	{
		type: 'text',
		name: 'percentMonthPension',
		className: 'pension',
		errorText: 'Enter login!',
		labelText: 'Ежемесячный % после создания капитала, $',
		disabled: true,
		value: 0,
	},
	{
		type: 'text',
		name: 'contribution',
		required: true,
		className: 'storage',
		errorText: 'Enter login!',
		labelText: 'Первоначальная инвестиция в $ <span class="star">*</span>',
		// value: 1000,
	},
	{
		type: 'text',
		name: 'addMonth',
		required: true,
		className: 'storage',
		errorText: 'Enter login!',
		labelText: 'Добавления каждый месяц в $ <span class="star">*</span>',
		// value: 1000,
	},
	{
		type: 'text',
		name: 'startCreateCapital',
		required: true,
		className: 'storage',
		errorText: 'Enter login!',
		labelText: 'Возраст начала создания капитала, лет <span class="star">*</span>',
		// value: 25,
	},
	{
		type: 'text',
		name: 'pension',
		required: true,
		className: 'storage',
		errorText: 'Enter login!',
		labelText: 'Возраст завершения создания капитала, лет <span class="star">*</span>',
		// value: 50,
	},
	{
		type: 'text',
		name: 'quantityAccum',
		className: 'storage',
		errorText: 'Enter login!',
		labelText: 'Количество лет создания капитала',
		disabled: true,
	},
	{
		type: 'text',
		name: 'hardPercentInYear',
		required: true,
		className: 'storage',
		errorText: 'Enter login!',
		labelText: 'Годовой сложный % в период создания капитала <span class="star">*</span>',
		value: '10%',
	},
	{
		type: 'text',
		name: 'percentMonth',
		className: 'storage',
		errorText: 'Enter login!',
		labelText: 'Ежемесячный % в период накопления создания капитала',
		disabled: true,
		value: 0,
	},

	{
		type: 'text',
		name: 'summ',
		className: 'storage',
		errorText: 'Enter login!',
		labelText: 'Сумма к моменту выхода на пенсию,$',
		disabled: true,
		value: 0,
	},
];
